SELECT * FROM STUDENTS
DROP TABLE STUDENTS


CREATE TABLE Students (
StudentID INT IDENTITY(1,1) PRIMARY KEY,
FirstName VARCHAR(100),
LastName VARCHAR(100),
Age INT 
)


SELECT * FROM Students 